// GENERATED BY ./generate_glpp_hpp.sh - 2022-01-04T19:53:11 CET
#pragma once

#include <GL/glew.h>

#include "glpp/Buffer.hpp"
#include "glpp/Debug.hpp"
#include "glpp/Drawing.hpp"
#include "glpp/Enums.hpp"
#include "glpp/Framebuffer.hpp"
#include "glpp/Pipeline.hpp"
#include "glpp/Program.hpp"
#include "glpp/Sampler.hpp"
#include "glpp/Shader.hpp"
#include "glpp/State.hpp"
#include "glpp/Texture.hpp"
#include "glpp/VertexArray.hpp"


#ifndef GLPP_NO_INLINE

	#define GLPP_INLINE
	#define GLPP_DECL inline
	#include "glpp/Buffer.cpp"
	#include "glpp/Debug.cpp"
	#include "glpp/Enums.cpp"
	#include "glpp/Framebuffer.cpp"
	#include "glpp/Program.cpp"
	#include "glpp/Sampler.cpp"
	#include "glpp/Shader.cpp"
	#include "glpp/Texture.cpp"
	#include "glpp/VertexArray.cpp"

#endif // (GLPP_NO_INLINE)
